### ISSUE TITLE
High resolution display issues

### ISSUE THREAD

**Issue by paulmozo** [MeltwaterArchive/editor#42]
Looks like there is an issue with the query builder when using a machine with high resolution, see screenshots:

![screenshot_11_5_13_11_53_pm](https://f.cloud.github.com/assets/5136707/1482375/19e8387e-46df-11e3-91f9-5037cfd7338a.png)
![screenshot_11_5_13_11_51_pm](https://f.cloud.github.com/assets/5136707/1482376/1f2e3612-46df-11e3-9a18-2fd3c4849cbf.png)

**Comment by michaldudek** [comment]
Hi Paul,

Thanks for reporting this. However, this has been solved several months ago - https://github.com/datasift/editor/issues/22 and https://github.com/datasift/editor/pull/21 .

Just to be sure (as there has been numerous updates in the meantime) I've checked now and all seems fine:

![zrzut ekranu 2013-11-6 o 17 52 31](https://f.cloud.github.com/assets/802141/1484248/570f8c6e-4704-11e3-9f24-0e394f0c89e9.png)

Are you using the latest version?

**Comment by paulmozo** [comment]
This was actually reported to us this morning by a customer, I simply created the issue on their behalf.

I'm guessing this is still an issue in certain circumstances.

**Comment by michaldudek** [comment]
Could you point me to a place where it is occurring or could you check what version is installed there?

**Comment by sreerajmobomo** [comment]
Hi Michal,

Actually we are using query builder with version 2.0. I saw that the latest version is 2.3.1. We will try the latest one soon.

Thanks
